### PR TITLE
Add comment syntax settings

### LINKED ISSUE #16: Incorrect comment character
When editing a sequence diagram with the `Diagram Sequence Rules` language syntax, the `cmd + /` default key binding adds a `/* … */` comment instead of a `# …` comment resulting in a parser error.

### PR DESCRIPTION
**Pull request by galenandrew**
This PR adds the specific comment syntax for both `sequence` and `dot` grammars.

fixes #16

### CODE REVIEW

**Comment by seflless** [comment]
Awesome, thanks! Will create a release shortly.

**Comment by seflless** [comment]
New release is up: https://github.com/francoislaberge/atom-diagrams/releases/tag/v0.28.4

**Comment by galenandrew** [comment]
Awesome!! Thank you for the quick release @francoislaberge!! 🙌 💯 :shipit:

**Comment by seflless** [comment]
My pleasure, I love a PR with a solution. It hadn't even occurred to me that you could do that. Way better now!

**Pull request merged**
